language: cpp
compiler:
        - gcc



install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi


addons:
  apt:
      sources:
        - ubuntu-toolchain-r-test
      packages:
        - gcc-4.8
        - g++-4.8
        - cmake
        - freeglut3-dev
        - libfreeimage3
        - libfreeimage-dev
        - libassimp-dev
        - libglew-dev
        - libxmu-dev
        - libxi-dev

before_script:
        - sudo find / -name ai_assert.h
        - sudo find / -name glew.h
        - sudo find / -name FreeImage.h
        - mkdir -p build
        - cd build
        - cmake -DCMAKE_BUILD_TYPE:STRING=Debug ..


script: make